#!/usr/bin/env php
<?php
declare(strict_types=1);

use RigStats\StatsApp\Console\ComputeAllocationCommand;
use RigStats\StatsApp\Serializers\AllocationsFactory;
use RigStats\StatsApp\Serializers\ExtractionsFactory;
use RigStats\StatsApp\Serializers\WellFluidErrorsFactory;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application();
$app->add(
    new ComputeAllocationCommand(
    // note: in a bigger app these dependencies could be autowired by DI container
        [
            new AllocationsFactory(),
            new WellFluidErrorsFactory(),
        ],
        [
            new ExtractionsFactory(1e-5),
        ],
    )
);
$app->run();
